# Generated by Django 5.2.1 on 2025-05-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='delay',
            field=models.CharField(default='.4s', max_length=200),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
